version: '3.3'
services:
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    volumes:
      - ./volumes/axonserver-data:/data
      - ./volumes/axonserver-events:/eventdata
      - ./volumes/axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'